apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.2.0
    init: confluentinc/confluent-init-container:2.4.0
  dataVolumeCapacity: 10Gi
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksqldb
      url: http://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url: http://connect.confluent.svc.cluster.local:8083
  configOverrides:
    server:
      - confluent.metrics.reporter.topic.retention.ms=86400000
      - confluent.metrics.reporter.topic.retention.bytes=522752000
      - confluent.reporters.telemetry.auto.enable=false
    jvm:
      - “-Xmx2g”
      - “-Xms1g”
  podTemplate:
    resources:
      requests:
        cpu: 1
        memory: 2G