---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent-2
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.2.0
    init: confluentinc/confluent-init-container:2.4.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  tls:
    secretRef: kafka-tls
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent-2
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.2.0
    init: confluentinc/confluent-init-container:2.4.0
  dataVolumeCapacity: 10Gi
  mountedSecrets:
    - secretRef: password-encoder-secret
  configOverrides:
    server:
      - auto.create.topics.enable=true
      - confluent.cluster.link.enable=true
      - password.encoder.secret=${file:/mnt/secrets/password-encoder-secret/password_encoder_secret:secret}
  metricReporter:
    enabled: true
    tls:
      enabled: true
  tls:
    secretRef: kafka-tls
  listeners:
    internal:
      tls:
        enabled: true
    external:
      tls:
        enabled: true
      externalAccess:
        type: loadBalancer
        loadBalancer:
          domain: alexsalvo1.com
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent-2.svc.cluster.local:2182
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent-2
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.2.0
    init: confluentinc/confluent-init-container:2.4.0
  tls:
    secretRef: kafka-tls
  dataVolumeCapacity: 10Gi
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent-2.svc.cluster.local:9071
      tls:
        enabled: true
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: alexsalvo1.com 
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: destination-kafka-rest
  namespace: confluent-2
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: http://kafka.confluent-2.svc.cluster.local:8090
    authentication:
      type: basic
      basic:
        secretRef: rest-credential
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: source-kafka-rest
  namespace: confluent-2
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: http://kafka.confluent.svc.cluster.local:8090
    authentication:
      type: basic
      basic:
        secretRef: rest-credential