#!/usr/bin/env bash

openssl genrsa -out sslcerts_autogenerated/ca-key.pem 2048

openssl req -new -key sslcerts_autogenerated/ca-key.pem -x509 \
  -days 1000 \
  -out sslcerts_autogenerated/ca.pem \
  -subj "/C=US/ST=CA/L=MountainView/O=Confluent/OU=Operator/CN=TestCA"

kubectl create secret tls ca-pair-sslcerts \
  --cert=sslcerts_autogenerated/ca.pem \
  --key=sslcerts_autogenerated/ca-key.pem -n $namespace


echo -n "jksPassword=$1" > jksPassword.txt

kubectl create secret generic kafka-tls \
--from-file=keystore.jks=sslcerts/kafka.server.keystore.jks \
--from-file=truststore.jks=sslcerts/kafka.server.truststore.jks \
--from-file=jksPassword.txt=jksPassword.txt -n $namespace

kubectl apply -f ./resources/confluent-platform-SSL.yaml
kubectl wait --for=condition=ready pods --all --namespace $namespace --timeout=90s
#kubectl get pods
#kubectl apply -f ./resources/secure-producer-app-data.yaml -n $namespace