#!/usr/bin/env bash

#kubectl create secret tls ca-pair-sslcerts \
#  --cert=resources/sslcerts/autogenerated/ca.pem \
#  --key=resources/sslcerts/autogenerated/ca-key.pem -n $namespace


#echo -n "jksPassword=$1" > resources/jksPassword.txt

#kubectl create secret generic kafka-tls \
#--from-file=keystore.jks=resources/sslcerts/custom/kafka.server.keystore.jks \
#--from-file=truststore.jks=resources/sslcerts/custom//kafka.server.truststore.jks \
#--from-file=jksPassword.txt=resources/jksPassword.txt -n $namespace


kubectl create secret generic kafka-tls \
  --from-file=fullchain.pem=resources/sslcerts/server/server.pem \
  --from-file=cacerts.pem=resources/sslcerts/ca/ca.pem \
  --from-file=privkey.pem=resources/sslcerts/server/server-key.pem \
  -n $namespace

kubectl apply -f ./resources/confluent-platform-SSL.yaml
kubectl wait --for=condition=ready pods --all --namespace $namespace --timeout=90s
#kubectl apply -f ./resources/secure-producer-app-data.yaml -n $namespace