apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: confluent-operator
  namespace: confluent
rules:
- apiGroups:
  - platform.confluent.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - secrets
  - secrets/finalizers
  - pods
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
---
# Change the service account subject to one that exists in your namespace
# Change the namespace to your namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: confluent-operator
  namespace: confluent
subjects:
- kind: ServiceAccount
  name: confluent-for-kubernetes # customize as required
  namespace: confluent # customize as required
roleRef:
  kind: Role
  name: confluent-operator
  apiGroup: rbac.authorization.k8s.io
